const code = [{code:'ICBC',name: '中国工商银行'},
{code:'ABC',name: '中国农业银行'},
{code:'CMBCHINA',name: '招商银行'},
{code:'CCB',name: '中国建设银行'},
{code:'BOCO',name: '交通银行'},
{code:'BOC',name: '中国银行'},
{code:'CMBC',name: '中国民生银行'},
{code:'CGB',name: '广发银行'},
{code:'HXB',name: '华夏银行'},
{code:'POST',name: '中国邮政储蓄银行'},
{code:'ECITIC',name: '中信银行'},	
{code:'CEB',name: '中国光大银行'},
{code:'PINGAN',name: '平安银行'},
{code:'CIB',name: '兴业银行'},
{code:'SPDB',name: '浦发银行'},
{code:'BCCB',name: '北京银行'},
{code:'BON',name: '南京银行'},
{code:'NBCB',name: '宁波银行'},
{code:'BEA',name: '东亚银行'},
{code:'SRCB',name: '上海农商银行'},
{code:'SHB',name: '上海银行'},
{code:'CZB',name: '浙商银行'},
{code:'TCCB',name: '天津银行'},
{code:'HSBANK',name: '徽商银行'},
{code:'HFBANK',name: '恒丰银行'},
{code:'CBHB',name: '渤海银行'},
{code:'JSB',name: '江苏银行'},
{code:'CITI',name: '花旗银行'},
{code:'THX',name: '贵阳银行'},
{code:'HANGSENGBANK',name: '恒生银行'},
{code:'GDNYBANK',name: '南粤银行'},
{code:'LZBANK',name: '兰州银行'},
];


export default code;
